<a href="https://colab.research.google.com/github/pedd1-Srividya/DS-AI-ML-And-Web-Devolopment-Practice/blob/master/DS_ML_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Basics of Python

In [ ]:
#comments
a=2
b=3
c=a+b #c is a variable and value of a and b has been added
'''
Multiline comment
Python is a case sensitive language
'''

'\nMultiline comment\nPython is a case sensitive language\n'

In [ ]:
#title print function
#syntax for print function
a=10
b=20
sum=a+b
print(sum)#valid synatx

30


In [ ]:
#printing hello world
print("Hello World")

Hello World


In [ ]:
# There are two parameters in print function
'''
1) end parameter
2) separated parameter
'''
# Print both statments in a single line
print('Hello World', end=' ')#Default value of end is '\n' (new line)
print('How r u?')
#separate two statements with @
print('rinex','gmail.com',sep='@')#Default value of sep is' '(space)

Hello World How r u?
rinex@gmail.com


In [ ]:
#Anything that can store any value in programming language is termed as variable
a=10# Here a is a variable
message='Hello World' # Here message is a variable
print(a)
print(message)
'''
Rules to write a variable
1) You cannot start the variable name with a anumber but you continue with it.
Ex: 1a - Invalid, a1- Valid
2) We cannot use keyboards as variable name.
Ex: print = 10(Invalid)
3) case sensitive
ex:
a=10
print(A)# Invalid syntax
a=10
print(a)# Valid syntax
'''

10
Hello World


'\nRules to write a variable\n1) You cannot start the variable name with a anumber but you continue with it.\nEx: 1a - Invalid, a1- Valid\n2) We cannot use keyboards as variable name.\nEx: print = 10(Invalid)\n3) case sensitive\nex:\na=10\nprint(A)# Invalid syntax\na=10\nprint(a)# Valid syntax\n'

# Basic Operators in python
1.Arthimetic Operators

2.Comparision Operators

3.Logical Operators

4.Assignment operators

In [ ]:
# @title Arthimetic Operators
'''
1) Addition(+)
2) Subtraction(-)
3) Division(/)
4) multiplication(*)
5) Modulus (Remainder)(%)
6) Floor Division(//)
7) Exponent(**)
'''
a=10
b=5
sum=a+b
print("sum is",sum)
diff=a-b
print("Difference is",diff)
qnt=a/b
print("Quotient is",qnt)
prod=a*b
print("Product is",prod)
mod=a%b
print("Remainder is",mod)
floor=a//b
print("Floor division is",floor)
exp=a**b
print("Exponent is",exp)


sum is 15
Difference is 5
Quotient is 2.0
Product is 50
Remainder is 0
Floor division is 2
Exponent is 100000


In [ ]:
# @title Comparision Operators
'''
1) Equal to(==)
2) Not Equal(!=)
3) Greater than(>)
4) Greater than or equal to(>=)
5) Lesser than(<)
6) Lesser than or equal to(<=)
'''
a=10
b=5
print(a==b)
print(a!=b)
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)


False
True
True
True
False
False


# Logical Operators

In [ ]:
# @title Logical Operators
'''
1) Logical AND(and)
2) Logical OR(or)
3) Logical NOT(not)
'''
#Get only the number greater than 5 and less than 10
num=int(input("Enter the number"))
cond=(num>5) and (num<10)
print(cond)

True


# CONDITIONAL OPERATORS
1.IF statement

2.IF ELSE statement

3.IF ELIF ELSE statement

In [ ]:
# @title syntax
if condition:
  statements
elif condition:
  statements
  ..
  ..
  ..
  ..
else:
  statements

In [ ]:
# @title Example1
#check if the number is greater than 0 or not
num=int(input("Enter a number"))
if num>0:
  print("number is greater than 0")
else:
  print("number is not greater than 0")


Enter a number5
number is greater than 0


In [ ]:
# @title Example2
#check if the number is +ve or -ve
num=int(input("Enter a number"))
if num>0:
  print("number is +ve")
elif num==0:
  print("number is 0")
else:
  print("number is -ve")


Enter a number2
number is +ve


In [ ]:
# @title Example3
#check if you are admin, then you have admin privilege else you have no access
username=input("Enter username")
admin_username='admin@321'
if username==admin_username:
  print("Welcome admin kindly enter your password")
  password=input("Enter password")
  admin_password='pass@321'
  if password==admin_password:
    print("Welcome admin, You have admin priviledge")
  else:
    print("Invalid password")
else:
  print("invalid username")

Enter usernameadmin@321
Welcome admin kindly enter your password
Enter passwordpass@321
Welcome admin, You have admin priviledge


In [ ]:
# @title Example4
#check if you user is eligible to vote (age >=18 )
age=int(input("Enter your age"))
if age>=18:
  print("user is Eligible to vote")
else:
  a=18-age
  print("User is not eligible to vote wait for",a,"years")


Enter your age15
User is not eligible to vote wait for 3 years


In [ ]:
# @title Example5
# check whether the given number is even or odd
num=int(input("Enter a number"))
if num%2==0:
  print("Number is even")
else:
  print("Number is odd")

Enter a number5
Number is odd


In [ ]:
# @title Example6
#Check if the number is Factor of 7
num=int(input("Enter a number"))
if num%7==0:
  print("Number is factor of 7")
else:
  print("Number is not a factor of 7")

Enter a number15
Number is not a factor of 7


In [ ]:
# @title Excercise1
#If the employee is working in the company for more than 5 years then he/she will get bonus of 50% to their current salary
work_experience=int(input("Enter your work experience"))
if work_experience>5:
  salary=float(input("Enter your current salary"))
  bonus=salary*0.5
  print("Your work experience is greater than 5 years so ur salary with bonus is:",salary+bonus)
else:
  print("No bonus")

Enter your work experience4
No bonus


In [ ]:
# @title Excercise2
#If the electricity units is less than 100 then no charge, else if the electricity unit is greater than 100 and lesser than
#200 then Rs.10 per unit. If the units is greater than 200 then Rs. 15 per unit
units=float(input("Enter the Electricity units"))
if units<=100:
  print("No Charge")
elif units>100 and units<=200:
  charge=(units-100)*10
  print("Electricity charge:",charge)
elif units>200:
  charge=1000+(units-200)*15
  print("Electricity charge:",charge)


Enter the Electricity units201
Electricity charge: 1015.0


In [ ]:
# @title Excercise3
# BMI Caluculator
# BMI=(Weight(KG))/(Height(M)**2)
# BMI <18.5 then Underweight
# BMI between 18.5 and 24.9 then normal weight
# BMI between 24.9 and 29.9 then overweight
# BMI >29.9 obese
height_m=float(input("Enter the height in meters"))
weight_kg=float(input("Enter the weight in kg"))
BMI=weight_kg/(height_m**2)
if BMI<18.5:
  print(f"Your BMI is {BMI} Underweight")
elif BMI>=18.5 and BMI<24.9:
  print(f"Your BMI is {BMI} NormalWeight")
elif BMI>=24.9 and BMI<29.9:
  print(f"Your BMI is {BMI} Overweight")
else:
  print(f"Your BMI is {BMI} obese")

Enter the height in meters1.61
Enter the weight in kg64
Your BMI is 24.690405462752206 NormalWeight


In [ ]:
# @title Excercise4
#Find whether the character is a vowel or a consonant
char=input("Enter any letter")
char_lower=char.lower()
vowel=['a','e','i','o','u']
if char_lower in vowel:
  print("The letter is vowel")
else:
  print("The letter is consonant")

Enter any letterA
The letter is vowel


# Datatype
1) Boolean
2) Number(int/float)
3) String
4) List
5) Dictionary

In [ ]:
# @title Boolean
a=True
b=False
print(type(a))

<class 'bool'>


In [ ]:
# @title Number
a=1
b=1.1
print(type(a))
print(type(b))

<class 'int'>
<class 'float'>


In [ ]:
# @title String
a='Hello world'
print(type(a))
print(a[0])
print(a[-1])
print(a[0:5])
print(a[6:])

<class 'str'>
H
d
Hello
world


In [ ]:
# @title Functions in String
a='My Name is abc'
print(a.lower())
print(a.upper())
print(len(a))
print(a.replace('abc','xyz'))

my name is abc
MY NAME IS ABC
14
My Name is xyz


In [ ]:
# @title Lists
emp_name=['sam','John','Ram','Adam']
print(emp_name)
print(emp_name[0])
print(emp_name[-1])
print(emp_name[1:3])

['sam', 'John', 'Ram', 'Adam']
sam
Adam
['John', 'Ram']


In [ ]:
# @title Dictionary: Key-value Pairs
employees=['adam','28','john','30','ram','28']
print(employees[3])
employees_list={'adam':28,'jhon':30,'ram':28}
print(employees_list['adam'])
print(employees_list.keys())
print(employees_list.values())
print(employees_list.items())



30
28
dict_keys(['adam', 'jhon', 'ram'])
dict_values([28, 30, 28])
dict_items([('adam', 28), ('jhon', 30), ('ram', 28)])


In [ ]:
# @title Exercise
#User Authentication
database={
            'user1':'pass@123',
            'user2':'pass@456',
            'user3':'pass@789'

          }
username=input("Enter the username")
if username in database.keys():
  password=input("Enter the password")
  if password in database[username]:
    print("Welcome", username)
  else:
    print("Invalid password")
else:
  print("Invalid username")

Enter the usernameuser1
Enter the passwordpass@123
Welcome user1


# Looping Statements

In [ ]:
'''
1) For loop (Whenever we know the no. of iterations)
2) While loop (Whenever we do not know thw no. of iterations) - Infinite loop
#Syntax for for loop
for initialization_variable in condition:
  statements
#syntax for while loop
initialization_variable=value
while condition:
  statememts
  '''

In [ ]:
#print Hello for 10 times
for i in range(10):
  print("Hello!")

Hello!
Hello!
Hello!
Hello!
Hello!
Hello!
Hello!
Hello!
Hello!
Hello!


In [ ]:
#print Hello for 10 times
i=0
while i<10:
  print('hello')
  i+=1

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello


In [ ]:
#print 0 to 10 numbers
for i in range(11):
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
#print 0 to 10 numbers
i=0
while i<11:
  print(i)
  i+=1

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
#print 1 to 10 numbers
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#print 1 to 10 numbers
i=1
while i<11:
  print(i)
  i+=1

1
2
3
4
5
6
7
8
9
10


In [ ]:
# print 5 to 10 numbers
for i in range(5,11,+1):
  print(i)

5
6
7
8
9
10


In [ ]:
# print 5 to 10 numbers
i=5
while i<=10:
  print(i)
  i+=1

5
6
7
8
9
10


In [ ]:
# print 10 to 1 numbers
for i in range(10,0,-1):
  print(i)

10
9
8
7
6
5
4
3
2
1


In [ ]:
# print 10 to 1 numbers
i=10
while i>=1:
  print(i)
  i-=1

10
9
8
7
6
5
4
3
2
1


In [ ]:
# print 5 to 50 bu only the 5 multiples
for i in range(5,51,+5):
  print(i)

5
10
15
20
25
30
35
40
45
50


In [ ]:
# print 5 to 50 bu only the 5 multiples
i=5
while i<=50:
  if i%5==0:
    print(i)
  i+=1

5
10
15
20
25
30
35
40
45
50


In [ ]:
# print 50 to 5 but only 5 multiples
for i in range(50,4,-5):
  print(i)

50
45
40
35
30
25
20
15
10
5


In [ ]:
# print 50 to 5 but only 5 multiples
i=50
while i>=5:
  if i%5==0:
    print(i)
  i-=1

50
45
40
35
30
25
20
15
10
5


In [ ]:
# print 17 to 170 but only 17 multiples
for i in range(17,171,+17):
  print(i)

17
34
51
68
85
102
119
136
153
170


In [ ]:
# print 17 to 170 but only 17 multiples
i=17
while i<=170:
  if i%17==0:
    print(i)
  i+=1

17
34
51
68
85
102
119
136
153
170


In [ ]:
# print 10 to 170 but only 13 multiples
for i in range(10,171):
  if i%13==0:
    print(i)

13
26
39
52
65
78
91
104
117
130
143
156
169


In [ ]:
# print 10 to 170 but only 13 multiples
i=10
while i<=170:
  if i%13==0:
    print(i)
  i+=1

13
26
39
52
65
78
91
104
117
130
143
156
169


In [ ]:
'''
*
*
*
*
*
'''
for i in range(5):
  print('*')

*
*
*
*
*


In [ ]:
i=1
while i<=5:
  print('*')
  i+=1

*
*
*
*
*


In [ ]:
'''
* * * * *
'''
for i in range(5):
  print('*', end=' ')

* * * * * 

In [ ]:
i=1
while i<=5:
  print('*',end=' ')
  i+=1

* * * * * 

In [ ]:
# @title Nested For Loop
'''
*****
*****
*****
*****
*****
'''
for i in range(5):
  for j in range(5):
    print('*' , end=' ')
  print(' ')


* * * * *  
* * * * *  
* * * * *  
* * * * *  
* * * * *  


In [ ]:
'''
*
**
***
****
*****
'''
for i in range(6):
  for j in range(i):
    print('*',end=' ')
  print(' ')

 
*  
* *  
* * *  
* * * *  
* * * * *  


In [ ]:
'''
*****
****
***
**
*
'''
for i in range(5,0,-1):
  for j in range(i):
    print('*',end=' ')
  print(' ')

* * * * *  
* * * *  
* * *  
* *  
*  


In [ ]:
'''
1
2 2
3 3 3
4 4 4 4
5 5 5 5 5
'''
for i in range(6):
  for j in range(i):
    print(i,end=' ')
  print(' ')

 
1  
2 2  
3 3 3  
4 4 4 4  
5 5 5 5 5  


In [ ]:
'''
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5
'''
for i in range(1,6):
  for j in range(1,i+1):
    print(j,end=' ')
  print(' ')

1  
1 2  
1 2 3  
1 2 3 4  
1 2 3 4 5  


In [ ]:
# Find the sum of the list using for loop
num_list=[34,34,6,56,34,656,67,54,5,7,98,32]
sum=0
for i in num_list:
  sum+=i
print(sum)


1083


In [ ]:
# program to find factorial of a number using while loop
fact=1
i=int(input("Enter a value"))
while(i>0):
  fact=fact*i
  i=i-1
print(fact)

Enter a value4
24


In [ ]:
# Check prime number
num=int(input("Enter the number"))
if num<=1:
  print("Number is not prime")
else:
  is_prime=True
  for i in range(2,num):
    if num%i==0:
      is_Prime=False
      break

  if is_prime:
    print("Number is prime")
  else:
    print("Number is not prime")


Enter the number2
Number is prime


In [ ]:
# @title Excercise
#Display Menu program
while True:
  print("Calculator ")
  print("Option 1 - Sum")
  print("Option 2 - Difference")
  print('Option 3 - Product')
  print('Option 4 - Quotient')
  print('Option 5 - Quit')
  option = int(input("enter your choice"))
  if option == 1:
    num1=int(input("enter number 1"))
    num2=int(input("Enter number 2"))
    sum=num1+num2
    print("Sum",sum)
  elif option==2:
    num1=int(input("enter number 1"))
    num2=int(input("Enter number 2"))
    diff=num1-num2
    print("Difference",diff)
  elif option==3:
    num1=int(input("enter number 1"))
    num2=int(input("Enter number 2"))
    product=num1*num2
    print("Product",product)
  elif option==4:
    num1=int(input("enter number 1"))
    num2=int(input("Enter number 2"))
    Quotient=num1/num2
    print("Quotient",Quotient)
  elif option==5:
    print("Thank you")
    break
  else:
    print("Invalid choice")


Calculator 
Option 1 - Sum
Option 2 - Difference
Option 3 - Product
Option 4 - Quotient
Option 5 - Quit
enter your choice3
enter number 15
Enter number 26
Product 30
Calculator 
Option 1 - Sum
Option 2 - Difference
Option 3 - Product
Option 4 - Quotient
Option 5 - Quit
enter your choice5
Thank you


In [ ]:
# @title Functions
'''
In python, a function is a reusable block of code that performs a specific task or a set of task.
'''

In [ ]:
# @title Example 1
# Code to return whether the given number is odd or even
def oddeven(num):
  if num%2==0:
    print("Even")
  else:
    print("Odd")
oddeven(5)

Odd


In [ ]:
# Code to return whether the given number is odd or even from user
def oddeven():
  while True:
    num=int(input("Enter the number"))
    if num==0:
      print("Number is zero")
      break
    elif num%2==0:
      print("Even")
    else:
      print("Odd")

In [ ]:
oddeven()

Enter the number5
Odd
Enter the number3
Odd
Enter the number4
Even
Enter the number8
Even
Enter the number0
Number is zero


In [ ]:
# @title Lambda Functions
'''def add(x,y):
  sum=x+y
  print(sum)'''
def addsub(x,y):
  sum=x+y
  print(sum)
  sub=x-y
  print(sub)
add=lambda x,y:x+y
#we can use lambda for only one expression(disadv)



In [ ]:
addsub(3,4)

7
-1


# Numpy

In [ ]:
# Numpy stands for Numerical python.
# Numpy is a python library used for working with arrays.
# Arrays is a collection of objects.

In [ ]:
# @title Steps to Import numpy and to use it
# Step 1: Import numpy library
import numpy as np
# Step 2: Convert list into a array
x=[1,2,3]
arr=np.array(x)
print(arr)

[1 2 3]


In [ ]:
# @title Example1
x=[1,2,3,4,5,6]
import numpy as np
arr=np.array(x)
print(arr+1)

[2 3 4 5 6 7]


In [ ]:
# @title Example2
# Find Remainder of each value when it is divided by 2
import numpy as np
x=[1,6,9,5]
arr=np.array(x)
print(arr%2)
# Find square of each array elements
print(arr**2)

[1 0 1 1]
[ 1 36 81 25]


In [ ]:
# @title Example3
# Converting a list into an array without declaring the list
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)
# Find Maximum value out of array 1
print(arr1.max())
print(np.max(arr1))
# Find Minimum value out of array 1
print(arr1.min())
print(np.min(arr1))
# Find average value out of array 1
print(arr1.mean())
print(np.mean(arr1))


[1 2 3 4 5]
[ 6  7  8  9 10]
5
5
1
1
3.0
3.0


In [ ]:
# @title Example4
# Find the dimension of the array
x=[1,2,3,4,5]
arr=np.array(x)
print(arr.ndim)

1


In [ ]:
# @title Example5
# Create 2D array
# Display 1st row
x=[[1,2,3,4,5],
   [6,7,8,9,10]]
arr=np.array(x)
print(arr.ndim)
print(arr[0])
print(arr[1])
print(arr[0:,0])

2
[1 2 3 4 5]
[ 6  7  8  9 10]
[1 6]


In [ ]:
# @title Steps to create multi dimensional arrays
# Step 1: Create Outermost array
x=[]
# step 2: Create Inner Array
x=[[],[]]
# Step 3: Create Inner most array
x=[[[],[]],[[],[]]]

In [ ]:
# @title Random Number Library
# Exploring the random number library
import numpy as np
from numpy import random
x=(random.randint(10))
arr=np.array(x)
print(arr)


4


In [ ]:
# @title Example1
# Create 1D array using random library
x=(random.randint(10, size=(5)))
arr=np.array(x)
print(arr)

[1 2 4 6 6]


In [ ]:
# title Example2
# Create 2D array using random library
x=(random.randint(10, size=(5,3)))
arr=np.array(x)
print(arr)

[[0 8 4]
 [6 3 8]
 [8 5 6]
 [3 8 3]
 [1 2 9]]


In [ ]:
# @title Example3
# Create 3D using random library
x=(random.randint(10, size=(2,5,3)))
arr=np.array(x)
print(arr)

[[[9 6 3]
  [7 8 7]
  [3 2 8]
  [0 2 6]
  [3 4 3]]

 [[4 1 1]
  [9 2 7]
  [8 8 4]
  [7 5 0]
  [9 6 5]]]


In [ ]:
# @A-Range function
'''
It is similar to range function but returns array
'''
import numpy as np
x=np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# @title Example1
# Change the datatype
x=np.arange(1,11,dtype=float)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# @title Example2
# print the factors from 5 to 50
x=np.arange(5,51,5)
print(x)

[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
# @title Example3
# Print array containing ones
x=np.ones(10, dtype=int)
print(x)

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
# @title Example4
# Print 2D array contatining zeros
x=np.zeros([2,4], dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]]


In [ ]:
# @title Example5
# Print Identity Matrix
x=np.identity(3, dtype=int)
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# @title Example6
x=np.eye(4,k=1,dtype=int)#k=offset value
print(x)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [ ]:
# Convert 1D array into 2D array
x=np.arange(10)
print(x)
'''
Factors of 10
1*10
10*1
5*2
2*5
'''
reshaped=x.reshape(5,2)
print("Reshaped Array:",reshaped)
print("Reshaped Array dimension:",reshaped.ndim)

[0 1 2 3 4 5 6 7 8 9]
Reshaped Array: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Reshaped Array dimension: 2


In [ ]:
# Convert 1D array into 3D array
x=np.arange(20)
print(x)
reshaped=x.reshape(2,5,2)
print("Reshaped Array:",reshaped)
print("Reshaped Array dimension:",reshaped.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array: [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
Reshaped Array dimension: 3


In [ ]:
# Convert 2D array into 3D array
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original array",x)
print("Original array dimension",x.ndim)
reshaped=x.reshape(10,1,1)
print("Reshaped array:",reshaped)
print("Reshaped array dimension:",reshaped.ndim)

Original array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Original array dimension 2
Reshaped array: [[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]]
Reshaped array dimension: 3


In [ ]:
# Convert 2D array into 1D array
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original array",x)
print("Original array dimension",x.ndim)
reshaped=x.reshape(10)
print("Reshaped array:",reshaped)
print("Reshaped array dimension:",reshaped.ndim)

Original array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Original array dimension 2
Reshaped array: [ 1  2  3  4  5  6  7  8  9 10]
Reshaped array dimension: 1


In [ ]:
# @title Accessing Array Elements
'''
1) Slicing
2) Integer Array Indexing
3) Boolean Array Indexing
'''


In [ ]:
# @title Slicing
import numpy as np
arr1=np.array([1,2,3])
# Access only 2 from the given array
print(arr1[1])
# Access only 3 from the given array
print(arr1[2])
arr2=np.array([[1,2,3],
               [4,5,6]])
# Access only 1 from the given array
print(arr2[0][0])
# Access only 5 from the given array
print(arr2[1][1])

2
3
1
5


In [ ]:
# @title Integer Array Indexing
import numpy as np
arr1=np.array([1,2,3])
# Access only 2 from the given array
print(arr1[1])
# Access only 3 from the given array
print(arr1[2])
arr2=np.array([[1,2,3],
               [4,5,6]])
# Access only 1 from the given array
print(arr2[0,0])
# Access only 5 from the given array
print(arr2[1,1])

2
3
1
5


In [ ]:
# @title Boolean Array Indexing
arr=np.array([[35,5,23,1,43,12,34,34,345,23,23],
              [12,34,34,23,23,34,76,54,76,87,56]])
print("Extract only those values which ar greater than 50")
cond=(arr>50)
print('Values that are greater than 50:',arr[cond])

Extract only those values which ar greater than 50
Values that are greater than 50: [345  76  54  76  87  56]


In [ ]:
arr=np.array([[35,5,23,1,43,12,34,34,345,23,23],
              [12,34,34,23,23,34,76,54,76,87,56]])
print("Extract only those values which are not divisible by 2 or basically extract odd numbers")
print("Values that are odd:",arr[arr%2!=0])

Extract only those values which are not divisible by 2 or basically extract odd numbers
Values that are odd: [ 35   5  23   1  43 345  23  23  23  23  87]


In [ ]:
# @title Student Report Dataset
import numpy as np
students_array=np.array([['Student_1',59,64,94,87,81],
                         ['Student_2',8,56,18,58,69],
                         ['Student_3',7,20,60,63,42],
                         ['Student_4',71,94,71,68,13],
                         ['Student_5',89,1,16,33,40],
                         ['Student_6',4,25,48,41,84],
                         ['Student_7',3,79,46,9,71],
                         ['Student_8',87,77,75,15,69],
                         ['Student_9',61,1,48,98,23],
                         ['Student_10',98,60,24,66,56],
                         ['Student_11',58,12,75,7,98],
                         ['Student_12',23,62,6,35,37],
                         ['Student_13',14,25,87,56,8],
                         ['Student_14',68,1,81,11,61],
                         ['Student_15',11,69,35,17,66]],dtype=object)

In [ ]:
# @title Task1
# Accessing all names of the students
#students_array[0:15,0]
students_array[:,0]

array(['Student_1', 'Student_2', 'Student_3', 'Student_4', 'Student_5',
       'Student_6', 'Student_7', 'Student_8', 'Student_9', 'Student_10',
       'Student_11', 'Student_12', 'Student_13', 'Student_14',
       'Student_15'], dtype=object)

In [ ]:
# @title Task2
# Find the average of subject 1
sub1=students_array[:,1]
print("Average of subject1 is:",sub1.mean())

Average of subject1 is: 44.06666666666667


In [ ]:
# @title Task3
# Find the average of subject 4
sub4=students_array[:,4]
print("Average of subject 4:",sub4.mean())

Average of subject 4: 44.266666666666666


In [ ]:
# @title Task4
# Find the average of student 7
student7=students_array[6,1:]
print("Average of Student 7:",student7.mean())

Average of Student 7: 41.6


In [ ]:
# @title Task5
# Find the average of student 7 for subject 2 to 4
student7=students_array[6,2:5]
print(student7.mean())

44.666666666666664


In [ ]:
# @title Task6
# Find the name andcount of students where subject 1 marks is greater than subject 2 marks
student=students_array[:,1]>students_array[:,2]
print(students_array[student,0])
print("Count:",len(students_array[student]))

['Student_5' 'Student_8' 'Student_9' 'Student_10' 'Student_11'
 'Student_14']
Count: 6


In [ ]:
# @title Task7
# Find the student average of first 10 students
average=students_array[0:10,1:]
print("Students average of first 10 students:",average.mean(axis=1))# Axis=1 means row wise average

# Find the subject average of first 10 students
average=students_array[0:10,1:]
print("Subject average of first 10 students:",average.mean(axis=0))# Axis=1 means column wise average

Students average of first 10 students: [77.0 41.8 38.4 63.4 35.8 40.4 41.6 64.6 46.2 60.8]
Subject average of first 10 students: [48.7 47.7 50.0 53.8 54.8]


In [69]:
# @title Task8
# Find the subject average of 1,3 and 4 subject
average=students_array[:,[1,3,4]]
print(average.mean(axis=0))

[44.06666666666667 52.266666666666666 44.266666666666666]


In [75]:
# @title Task9
# Find the subject average of student 5 to student 14
average=students_array[4:14,1:]
print(average.mean(axis=0))

[50.5 34.3 50.6 37.1 54.7]


In [80]:
# @title Task10
# Find all the student names who scored higher than student 15 in both subject1 and subject 2
student15_1=students_array[14,1]
sub1=students_array[:,1]
student15_2=students_array[14,2]
sub2=students_array[:,2]
student15=(sub1>student15_1) & (sub2>student15_2)
print(students_array[student15,0:3])

[['Student_4' 71 94]
 ['Student_8' 87 77]]


In [96]:
# @title Task11
# Find all the student names who scored higher than student 11 either in subject 1 or subject 5
student11_1=students_array[10,1]
sub1=students_array[:,1]
student11_5=students_array[10,5]
sub5=students_array[:,5]
student11=(sub1>student11_1) | (sub5>student11_5)
print(students_array[student11,0:3])

[['Student_1' 59 64]
 ['Student_4' 71 94]
 ['Student_5' 89 1]
 ['Student_8' 87 77]
 ['Student_9' 61 1]
 ['Student_10' 98 60]
 ['Student_14' 68 1]]
